### ISSUE TITLE
REQUEST: deploy prow for mimir

### ISSUE THREAD

**Issue by lucklove** [ti-community-infra/configs#307]
### GitHub Repo Name
mimir

### Which plugins do you want to deploy
You can find all available plugins in [this manual book](https://book.prow.tidb.io/).

- hold
- wip
- tide
- lifecycle

### Requirements
- [x] I have carefully read the instructions for the plugin I want to use.
- [x] I agree to leave the plugin configuration to be maintained by sig-ti-community-infra.

### TODO
- [ ] @ti-community-infra/sig-community-infra  Add the requested plugin configuration
- [ ] @ti-community-infra/sig-community-infra  Add repository admin to Robots
- [ ] @ti-community-infra/sig-community-infra  Turn off the old robot function

**Comment by lucklove** [comment]
Please add following users as commiter:
- lucklove
- mashenjun
- HunaToALice
- kaixu120811

**Comment by hi-rustin** [comment]
/close 

GitHub comes with features that can be used.
