### ISSUE TITLE
ti-chi-bot should not work on the repos that was not be configed.

### ISSUE THREAD

**Issue by Mini256** [ti-community-infra/configs#899]
## Bug Report

- [x] I have searched the issues of this repository and believe that this is not a duplicate.

### Related link

- Which project: pingcap/ossinsight-lite

- PR or Issue Link: https://github.com/pingcap/ossinsight-lite/pull/67#issuecomment-1582062857

### What is expected?

ti-chi-bot should not work on the repos that was not be configed.

### What is actually happening?

<img width="935" alt="image" src="https://github.com/ti-community-infra/configs/assets/5086433/9d1228dc-bb71-4c38-9ebd-f699ce768d95">

**Comment by wuhuizuo** [comment]
@Mini256 It disappeared. Please reopen the issue when it happens again.
